### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by chraibi** [PedestrianDynamics/SingleFileMovementAnalysis#6]
Add type hints everywhere to increase the readability of the scripts. 
Use [mypy](https://mypy.readthedocs.io/en/stable/getting_started.html).

For orientation, you can use this [mypy-file](https://github.com/PedestrianDynamics/pedpy/blob/main/mypy.ini) and *modify* it accordingly.

**Comment by RudinaMSubaih** [comment]
Thanks, Mohcine. All the scripts are updated with the type hints.
