### ISSUE TITLE
Unnecessary loadtxt in script

### ISSUE THREAD

**Issue by chraibi** [PedestrianDynamics/SingleFileMovementAnalysis#7]
This [line](https://github.com/PedestrianDynamics/SingleFileMovementAnalysis/blob/main/scripts/01_trajectory_data_preperation/00_transformation_additional.py#L90) uses parameters that are not passed to the function as arguments. 
Moreover, it seems that the data are read in the main loop, so this additional reading here is probably not correct.

**Comment by RudinaMSubaih** [comment]
Done
